kind: PersistentVolume
apiVersion: v1
metadata:
  name: chrono-data
  labels:
    type: local
spec:
  storageClassName: hdd-ext4
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/chrono"
