kind: PersistentVolume
apiVersion: v1
metadata:
  name: ssd-ext4
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
