kind: PersistentVolume
apiVersion: v1
metadata:
  name: kapdata
  labels:
    type: local
spec:
  storageClassName: local-storage2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kap"
